dsadsa
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@156 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/matc/configure b/matc/configure
--- a/matc/configure
+++ b/matc/configure
@@ -6020,6 +6020,17 @@ if test "${with_64bits+set}" = set; then
 
 fi;
 
+
+if test -z "$host"; then
+  host=unknown
+fi
+canonical_host_type=$host
+if test "$host" = unknown; then
+  { { echo "$as_me:$LINENO: error: unknown system type, your build will most likely be screwed. quitting." >&5
+echo "$as_me: error: unknown system type, your build will most likely be screwed. quitting." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 B64CFLAGS=
 B64FCFLAGS=
 B64F77FLAGS=
