fixed acx_elmer
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@157 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/eio/configure b/eio/configure
--- a/eio/configure
+++ b/eio/configure
@@ -5135,6 +5135,17 @@ if test "${with_64bits+set}" = set; then
 
 fi;
 
+
+if test -z "$host"; then
+  host=unknown
+fi
+canonical_host_type=$host
+if test "$host" = unknown; then
+  { { echo "$as_me:$LINENO: error: unknown system type, your build will most likely be screwed. quitting." >&5
+echo "$as_me: error: unknown system type, your build will most likely be screwed. quitting." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 B64CFLAGS=
 B64FCFLAGS=
 B64F77FLAGS=
@@ -5724,7 +5735,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_verb"
-(eval echo $as_me:5727: \"$ac_link\") >&5
+(eval echo $as_me:5738: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -5808,7 +5819,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_cv_prog_fc_v"
-(eval echo $as_me:5811: \"$ac_link\") >&5
+(eval echo $as_me:5822: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
