post: add gfortran + FTGL changes + add destdir.
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@3652 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/post/configure b/post/configure
--- a/post/configure
+++ b/post/configure
@@ -4321,7 +4321,7 @@ ac_compile='$FC -c $FCFLAGS $ac_fcflags_srcext conftest.$ac_ext >&5'
 ac_link='$FC -o conftest$ac_exeext $FCFLAGS $LDFLAGS $ac_fcflags_srcext conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_fc_compiler_gnu
 if test -n "$ac_tool_prefix"; then
-  for ac_prog in xlf90 pathf90 ifort ifc f90 g95
+  for ac_prog in gfortran xlf90 pathf90 ifort ifc f90 g95
   do
     # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
 set dummy $ac_tool_prefix$ac_prog; ac_word=$2
@@ -4365,7 +4365,7 @@ fi
 fi
 if test -z "$FC"; then
   ac_ct_FC=$FC
-  for ac_prog in xlf90 pathf90 ifort ifc f90 g95
+  for ac_prog in gfortran xlf90 pathf90 ifort ifc f90 g95
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -9663,18 +9663,18 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
 acx_ftgl_h_ok=no
-if test "${ac_cv_header_FTGL_h+set}" = set; then
-  { echo "$as_me:$LINENO: checking for FTGL.h" >&5
-echo $ECHO_N "checking for FTGL.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_FTGL_h+set}" = set; then
+if test "${ac_cv_header_FTGL_ftgl_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for FTGL/ftgl.h" >&5
+echo $ECHO_N "checking for FTGL/ftgl.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_FTGL_ftgl_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_FTGL_h" >&5
-echo "${ECHO_T}$ac_cv_header_FTGL_h" >&6; }
+{ echo "$as_me:$LINENO: result: $ac_cv_header_FTGL_ftgl_h" >&5
+echo "${ECHO_T}$ac_cv_header_FTGL_ftgl_h" >&6; }
 else
   # Is the header compilable?
-{ echo "$as_me:$LINENO: checking FTGL.h usability" >&5
-echo $ECHO_N "checking FTGL.h usability... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking FTGL/ftgl.h usability" >&5
+echo $ECHO_N "checking FTGL/ftgl.h usability... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -9682,7 +9682,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <FTGL.h>
+#include <FTGL/ftgl.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (ac_try="$ac_compile"
@@ -9714,15 +9714,15 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 echo "${ECHO_T}$ac_header_compiler" >&6; }
 
 # Is the header present?
-{ echo "$as_me:$LINENO: checking FTGL.h presence" >&5
-echo $ECHO_N "checking FTGL.h presence... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking FTGL/ftgl.h presence" >&5
+echo $ECHO_N "checking FTGL/ftgl.h presence... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <FTGL.h>
+#include <FTGL/ftgl.h>
 _ACEOF
 if { (ac_try="$ac_cpp conftest.$ac_ext"
 case "(($ac_try" in
@@ -9755,25 +9755,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6; }
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: FTGL.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: FTGL.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: FTGL.h: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: FTGL/ftgl.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: FTGL/ftgl.h: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: FTGL.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: FTGL.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: FTGL.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: FTGL.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: FTGL.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: FTGL.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: FTGL.h: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: FTGL/ftgl.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: FTGL/ftgl.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: FTGL/ftgl.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: FTGL/ftgl.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: FTGL/ftgl.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: FTGL/ftgl.h: in the future, the compiler will take precedence" >&2;}
     ( cat <<\_ASBOX
 ## ------------------------- ##
 ## Report this to jpr@csc.fi ##
@@ -9782,18 +9782,18 @@ _ASBOX
      ) | sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-{ echo "$as_me:$LINENO: checking for FTGL.h" >&5
-echo $ECHO_N "checking for FTGL.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_FTGL_h+set}" = set; then
+{ echo "$as_me:$LINENO: checking for FTGL/ftgl.h" >&5
+echo $ECHO_N "checking for FTGL/ftgl.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_FTGL_ftgl_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header_FTGL_h=$ac_header_preproc
+  ac_cv_header_FTGL_ftgl_h=$ac_header_preproc
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_FTGL_h" >&5
-echo "${ECHO_T}$ac_cv_header_FTGL_h" >&6; }
+{ echo "$as_me:$LINENO: result: $ac_cv_header_FTGL_ftgl_h" >&5
+echo "${ECHO_T}$ac_cv_header_FTGL_ftgl_h" >&6; }
 
 fi
-if test $ac_cv_header_FTGL_h = yes; then
+if test $ac_cv_header_FTGL_ftgl_h = yes; then
   acx_ftgl_h_ok=yes
 fi
 
@@ -9802,19 +9802,19 @@ fi
 if test "$acx_ftgl_h_ok" = no; then
    { echo "$as_me:$LINENO: result:
    ***************************************
-   ***    WARNING: FTGL.h not found    ***
+   *** WARNING: FTGL/ftgl.h not found  ***
    ***  FreeType2 rendering disabled   ***
    ***          Try adding:            ***
-   ***  -I/path/to FTGL.h in CXXFLAGS  ***
+   *** -I/path/to FTGL/ftgl.h in CXXFLAGS ***
    ***         and reconfigure         ***
    ***************************************
   " >&5
 echo "${ECHO_T}
    ***************************************
-   ***    WARNING: FTGL.h not found    ***
+   *** WARNING: FTGL/ftgl.h not found  ***
    ***  FreeType2 rendering disabled   ***
    ***          Try adding:            ***
-   ***  -I/path/to FTGL.h in CXXFLAGS  ***
+   *** -I/path/to FTGL/ftgl.h in CXXFLAGS ***
    ***         and reconfigure         ***
    ***************************************
   " >&6; }
