make dist fixes
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@639 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/post/configure b/post/configure
--- a/post/configure
+++ b/post/configure
@@ -6986,7 +6986,9 @@ _ACEOF
         :
 else
         acx_matc_ok=no
-
+        { { echo "$as_me:$LINENO: error: Couldn't link to MATC, make sure that libmatc is available and it works with your compiler." >&5
+echo "$as_me: error: Couldn't link to MATC, make sure that libmatc is available and it works with your compiler." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
