ElmerPost: Changed FTGL/ftgl.h to FTGL/FTGL.h in the configure script
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@3668 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/post/configure b/post/configure
--- a/post/configure
+++ b/post/configure
@@ -9664,8 +9664,8 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 acx_ftgl_h_ok=no
 if test "${ac_cv_header_FTGL_ftgl_h+set}" = set; then
-  { echo "$as_me:$LINENO: checking for FTGL/ftgl.h" >&5
-echo $ECHO_N "checking for FTGL/ftgl.h... $ECHO_C" >&6; }
+  { echo "$as_me:$LINENO: checking for FTGL/FTGL.h" >&5
+echo $ECHO_N "checking for FTGL/FTGL.h... $ECHO_C" >&6; }
 if test "${ac_cv_header_FTGL_ftgl_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
@@ -9673,8 +9673,8 @@ fi
 echo "${ECHO_T}$ac_cv_header_FTGL_ftgl_h" >&6; }
 else
   # Is the header compilable?
-{ echo "$as_me:$LINENO: checking FTGL/ftgl.h usability" >&5
-echo $ECHO_N "checking FTGL/ftgl.h usability... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking FTGL/FTGL.h usability" >&5
+echo $ECHO_N "checking FTGL/FTGL.h usability... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -9682,7 +9682,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <FTGL/ftgl.h>
+#include <FTGL/FTGL.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (ac_try="$ac_compile"
@@ -9714,15 +9714,15 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 echo "${ECHO_T}$ac_header_compiler" >&6; }
 
 # Is the header present?
-{ echo "$as_me:$LINENO: checking FTGL/ftgl.h presence" >&5
-echo $ECHO_N "checking FTGL/ftgl.h presence... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking FTGL/FTGL.h presence" >&5
+echo $ECHO_N "checking FTGL/FTGL.h presence... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <FTGL/ftgl.h>
+#include <FTGL/FTGL.h>
 _ACEOF
 if { (ac_try="$ac_cpp conftest.$ac_ext"
 case "(($ac_try" in
@@ -9755,25 +9755,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6; }
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: FTGL/ftgl.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: FTGL/ftgl.h: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/FTGL.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: FTGL/FTGL.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/FTGL.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: FTGL/FTGL.h: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: FTGL/ftgl.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: FTGL/ftgl.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: FTGL/ftgl.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: FTGL/ftgl.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: FTGL/ftgl.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: FTGL/ftgl.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: FTGL/ftgl.h: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/FTGL.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: FTGL/FTGL.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/FTGL.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: FTGL/FTGL.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/FTGL.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: FTGL/FTGL.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/FTGL.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: FTGL/FTGL.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/FTGL.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: FTGL/FTGL.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FTGL/FTGL.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: FTGL/FTGL.h: in the future, the compiler will take precedence" >&2;}
     ( cat <<\_ASBOX
 ## ------------------------- ##
 ## Report this to jpr@csc.fi ##
@@ -9782,8 +9782,8 @@ _ASBOX
      ) | sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-{ echo "$as_me:$LINENO: checking for FTGL/ftgl.h" >&5
-echo $ECHO_N "checking for FTGL/ftgl.h... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking for FTGL/FTGL.h" >&5
+echo $ECHO_N "checking for FTGL/FTGL.h... $ECHO_C" >&6; }
 if test "${ac_cv_header_FTGL_ftgl_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -9802,19 +9802,19 @@ fi
 if test "$acx_ftgl_h_ok" = no; then
    { echo "$as_me:$LINENO: result:
    ***************************************
-   *** WARNING: FTGL/ftgl.h not found  ***
+   *** WARNING: FTGL/FTGL.h not found  ***
    ***  FreeType2 rendering disabled   ***
    ***          Try adding:            ***
-   *** -I/path/to FTGL/ftgl.h in CXXFLAGS ***
+   *** -I/path/to FTGL/FTGL.h in CXXFLAGS ***
    ***         and reconfigure         ***
    ***************************************
   " >&5
 echo "${ECHO_T}
    ***************************************
-   *** WARNING: FTGL/ftgl.h not found  ***
+   *** WARNING: FTGL/FTGL.h not found  ***
    ***  FreeType2 rendering disabled   ***
    ***          Try adding:            ***
-   *** -I/path/to FTGL/ftgl.h in CXXFLAGS ***
+   *** -I/path/to FTGL/FTGL.h in CXXFLAGS ***
    ***         and reconfigure         ***
    ***************************************
   " >&6; }
