added experimental c++ library check...
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@943 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/fem/configure b/fem/configure
--- a/fem/configure
+++ b/fem/configure
@@ -5141,214 +5141,48 @@ echo "${ECHO_T}$acx_stdcxx_lib_ok" >&6; }
 	LIBS="$save_LIBS"
 fi
 
-if test $acx_stdcxxlib_ok = no; then
-	{ echo "$as_me:$LINENO: checking for main in -lstdc++" >&5
-echo $ECHO_N "checking for main in -lstdc++... $ECHO_C" >&6; }
-if test "${ac_cv_lib_stdcpp_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lstdc++  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-
-int
-main ()
-{
-main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_stdcpp_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_stdcpp_main=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_stdcpp_main" >&5
-echo "${ECHO_T}$ac_cv_lib_stdcpp_main" >&6; }
-if test $ac_cv_lib_stdcpp_main = yes; then
-
-				   STDCXX_LIBS="-lstdc++"
-			           acx_stdcxxlib_ok=yes
-
+if test x$CXX = x; then
+	{ { echo "$as_me:$LINENO: error: No C++ compiler found... major error" >&5
+echo "$as_me: error: No C++ compiler found... major error" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
-fi
+{ echo "$as_me:$LINENO: checking for C++ linker flags" >&5
+echo $ECHO_N "checking for C++ linker flags... $ECHO_C" >&6; }
+case $CXX in
+   xl*)
+	acx_cxx_verbose_flag="-V"
+   ;;
+   *)
+	acx_cxx_verbose_flag="-v"
+   ;;
+esac
 
-if test $acx_stdcxxlib_ok = no; then
-	{ echo "$as_me:$LINENO: checking for main in -lCstd" >&5
-echo $ECHO_N "checking for main in -lCstd... $ECHO_C" >&6; }
-if test "${ac_cv_lib_Cstd_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lCstd  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
+printf "int main(int argc, char **argv) { return(1); }" > test.cpp
 
+acx_cxx_verbose_out=`$CXX $acx_cxx_verbose_flag test.cpp 2>&1 |grep -e ' -l'`
+acx_cxx_libs=""
 
-int
-main ()
-{
-main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_Cstd_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
+for acx_cxx_ldflag in $acx_cxx_verbose_out; do
+    case $acx_cxx_ldflag in
+	[\\/]*.a | ?:[\\/]*.a)
+	   acx_cxx_libs="$acx_cxx_libs $acx_cxx_ldflag"
+	;;
+        # Ignore these flags.
+        -lang* | -lcrt*.o | -lc | -lgcc | -libmil | -LANG:=*)
+	;;
+	-[lLR]*)
+	   acx_cxx_libs="$acx_cxx_libs $acx_cxx_ldflag"
+        ;;
+	# ignore everything else
+    esac
+done
 
-ac_cv_lib_Cstd_main=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_Cstd_main" >&5
-echo "${ECHO_T}$ac_cv_lib_Cstd_main" >&6; }
-if test $ac_cv_lib_Cstd_main = yes; then
+rm test.cpp
 
-				   STDCXX_LIBS="-lCstd"
-			           acx_stdcxxlib_ok=yes
-
-fi
-
-fi
-
-if test $acx_stdcxxlib_ok = no; then
-	{ echo "$as_me:$LINENO: checking for main in -lC" >&5
-echo $ECHO_N "checking for main in -lC... $ECHO_C" >&6; }
-if test "${ac_cv_lib_C_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lC  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-
-int
-main ()
-{
-main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_C_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_C_main=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_C_main" >&5
-echo "${ECHO_T}$ac_cv_lib_C_main" >&6; }
-if test $ac_cv_lib_C_main = yes; then
-
-				   STDCXX_LIBS="-lC"
-			           acx_stdcxxlib_ok=yes
-
-fi
-
-fi
-
-if test $acx_stdcxxlib_ok = no; then
-	{ echo "$as_me:$LINENO: WARNING: Couldn't find std c++ library that is needed for linking." >&5
-echo "$as_me: WARNING: Couldn't find std c++ library that is needed for linking." >&2;}
-fi
+{ echo "$as_me:$LINENO: result: $acx_cxx_libs" >&5
+echo "${ECHO_T}$acx_cxx_libs" >&6; }
+STDCXX_LIBS=$acx_cxx_libs
 
 LIBS=$acx_check_stdcxxlib_save_LIBS
 
