sad
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@474 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/fem/configure b/fem/configure
--- a/fem/configure
+++ b/fem/configure
@@ -649,11 +649,6 @@ MAINTAINER_MODE_TRUE
 MAINTAINER_MODE_FALSE
 MAINT
 canonical_host_type
-BOURNE_SHELL
-RANLIB
-ac_ct_RANLIB
-AR
-ARFLAGS
 CC
 CFLAGS
 LDFLAGS
@@ -670,8 +665,6 @@ AMDEPBACKSLASH
 CCDEPMODE
 am__fastdepCC_TRUE
 am__fastdepCC_FALSE
-BASIC_CPP
-CPP
 CXX
 CXXFLAGS
 CCC
@@ -685,6 +678,13 @@ ac_ct_FC
 F77
 FFLAGS
 ac_ct_F77
+BOURNE_SHELL
+RANLIB
+ac_ct_RANLIB
+AR
+ARFLAGS
+BASIC_CPP
+CPP
 GREP
 EGREP
 USE_64BIT_ARCH_TRUE
@@ -2455,6 +2455,7 @@ fi
 
 
 
+
 echo "$as_me:$LINENO: checking for answer to meaning of life" >&5
 echo $ECHO_N "checking for answer to meaning of life... $ECHO_C" >&6
 echo "$as_me:$LINENO: result: 42" >&5
@@ -2635,133 +2636,6 @@ echo "${ECHO_T}optimized" >&6
   fi
 fi
 
-
-
-
-case "$canonical_host_type" in
-  *solaris* | *sun*)
-		BOURNE_SHELL="bash"
-  ;;
-  *)
-	BOURNE_SHELL="sh"
-  ;;
-esac
-
-
-
-if test -n "$ac_tool_prefix"; then
-  # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
-set dummy ${ac_tool_prefix}ranlib; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_RANLIB+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$RANLIB"; then
-  ac_cv_prog_RANLIB="$RANLIB" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_RANLIB="${ac_tool_prefix}ranlib"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-RANLIB=$ac_cv_prog_RANLIB
-if test -n "$RANLIB"; then
-  echo "$as_me:$LINENO: result: $RANLIB" >&5
-echo "${ECHO_T}$RANLIB" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-fi
-if test -z "$ac_cv_prog_RANLIB"; then
-  ac_ct_RANLIB=$RANLIB
-  # Extract the first word of "ranlib", so it can be a program name with args.
-set dummy ranlib; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_ac_ct_RANLIB+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$ac_ct_RANLIB"; then
-  ac_cv_prog_ac_ct_RANLIB="$ac_ct_RANLIB" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_ac_ct_RANLIB="ranlib"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-ac_ct_RANLIB=$ac_cv_prog_ac_ct_RANLIB
-if test -n "$ac_ct_RANLIB"; then
-  echo "$as_me:$LINENO: result: $ac_ct_RANLIB" >&5
-echo "${ECHO_T}$ac_ct_RANLIB" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  if test "x$ac_ct_RANLIB" = x; then
-    RANLIB=":"
-  else
-    if test "$build" != "$host"; then
-      { echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
-whose name does not start with the host triplet.  If you think this
-configuration is useful to you, please write to autoconf@gnu.org." >&5
-echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
-whose name does not start with the host triplet.  If you think this
-configuration is useful to you, please write to autoconf@gnu.org." >&2;}
-    fi
-    RANLIB=$ac_ct_RANLIB
-  fi
-else
-  RANLIB="$ac_cv_prog_RANLIB"
-fi
-
-
-# fixme: do something more intelligent here
-echo "$as_me:$LINENO: checking for ar" >&5
-echo $ECHO_N "checking for ar... $ECHO_C" >&6
-if test -z "$AR"; then
-        AR='ar'
-	acx_ar_userdefined=no
-else
-	acx_ar_userdefined=yes
-fi
-
-echo "$as_me:$LINENO: result: $AR" >&5
-echo "${ECHO_T}$AR" >&6
-
-echo "$as_me:$LINENO: checking for ar flags" >&5
-echo $ECHO_N "checking for ar flags... $ECHO_C" >&6
-if test -z "$ARFLAGS"; then
-  ARFLAGS="cru"
-fi
-
-echo "$as_me:$LINENO: result: $ARFLAGS" >&5
-echo "${ECHO_T}$ARFLAGS" >&6
 
 
 ac_ext=c
@@ -3767,95 +3641,6 @@ else
 fi
 
 
-
-# sun cc -E leaves nasty # comment that chokes the fortran compiler, so we have to hope
-# that ye olde cpp is present.
-echo "$as_me:$LINENO: checking for /lib/cpp" >&5
-echo $ECHO_N "checking for /lib/cpp... $ECHO_C" >&6
-if test "${ac_cv_file__lib_cpp+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "/lib/cpp"; then
-  ac_cv_file__lib_cpp=yes
-else
-  ac_cv_file__lib_cpp=no
-fi
-fi
-echo "$as_me:$LINENO: result: $ac_cv_file__lib_cpp" >&5
-echo "${ECHO_T}$ac_cv_file__lib_cpp" >&6
-if test $ac_cv_file__lib_cpp = yes; then
-  TRADITIONAL_CPP=yes
-else
-  TRADITIONAL_CPP=no
-fi
-
-
-if test "$TRADITIONAL_CPP" != "yes"; then
-   # Extract the first word of "cpp", so it can be a program name with args.
-set dummy cpp; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_BASIC_CPP+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$BASIC_CPP"; then
-  ac_cv_prog_BASIC_CPP="$BASIC_CPP" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_BASIC_CPP="yes"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  test -z "$ac_cv_prog_BASIC_CPP" && ac_cv_prog_BASIC_CPP="no"
-fi
-fi
-BASIC_CPP=$ac_cv_prog_BASIC_CPP
-if test -n "$BASIC_CPP"; then
-  echo "$as_me:$LINENO: result: $BASIC_CPP" >&5
-echo "${ECHO_T}$BASIC_CPP" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-   if test "$BASIC_CPP" = yes; then
-       CPP=cpp
-   else
-       { { echo "$as_me:$LINENO: error: Traditional cpp not found, just have to exit for for now." >&5
-echo "$as_me: error: Traditional cpp not found, just have to exit for for now." >&2;}
-   { (exit 1); exit 1; }; }
-   fi
-else
-   CPP="/lib/cpp"
-fi
-
-case "$canonical_host_type" in
-  *-*-cygwin* | *-*-mingw*)
-	TRADITIONAL_CPP_FLAGS="-traditional-cpp"
-  ;;
-  *-*-linux* | *-*-gnu*)
-	TRADITIONAL_CPP_FLAGS="-traditional-cpp"
-  ;;
-  *)
-	TRADITIONAL_CPP_FLAGS=""
-  ;;
-esac
-
-
-
 ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4534,7 +4319,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4537:" \
+echo "$as_me:4322:" \
      "checking for Fortran compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version >&5\"") >&5
@@ -4781,7 +4566,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4784:" \
+echo "$as_me:4569:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version >&5\"") >&5
@@ -4924,6 +4709,224 @@ ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+
+
+case "$canonical_host_type" in
+  *solaris* | *sun*)
+		BOURNE_SHELL="bash"
+  ;;
+  *)
+	BOURNE_SHELL="sh"
+  ;;
+esac
+
+
+
+if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
+set dummy ${ac_tool_prefix}ranlib; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_RANLIB+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$RANLIB"; then
+  ac_cv_prog_RANLIB="$RANLIB" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_RANLIB="${ac_tool_prefix}ranlib"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+RANLIB=$ac_cv_prog_RANLIB
+if test -n "$RANLIB"; then
+  echo "$as_me:$LINENO: result: $RANLIB" >&5
+echo "${ECHO_T}$RANLIB" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+fi
+if test -z "$ac_cv_prog_RANLIB"; then
+  ac_ct_RANLIB=$RANLIB
+  # Extract the first word of "ranlib", so it can be a program name with args.
+set dummy ranlib; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_ac_ct_RANLIB+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ac_ct_RANLIB"; then
+  ac_cv_prog_ac_ct_RANLIB="$ac_ct_RANLIB" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_ac_ct_RANLIB="ranlib"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+ac_ct_RANLIB=$ac_cv_prog_ac_ct_RANLIB
+if test -n "$ac_ct_RANLIB"; then
+  echo "$as_me:$LINENO: result: $ac_ct_RANLIB" >&5
+echo "${ECHO_T}$ac_ct_RANLIB" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  if test "x$ac_ct_RANLIB" = x; then
+    RANLIB=":"
+  else
+    if test "$build" != "$host"; then
+      { echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&5
+echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&2;}
+    fi
+    RANLIB=$ac_ct_RANLIB
+  fi
+else
+  RANLIB="$ac_cv_prog_RANLIB"
+fi
+
+
+# fixme: do something more intelligent here
+echo "$as_me:$LINENO: checking for ar" >&5
+echo $ECHO_N "checking for ar... $ECHO_C" >&6
+if test -z "$AR"; then
+        AR='ar'
+	acx_ar_userdefined=no
+else
+	acx_ar_userdefined=yes
+fi
+
+echo "$as_me:$LINENO: result: $AR" >&5
+echo "${ECHO_T}$AR" >&6
+
+echo "$as_me:$LINENO: checking for ar flags" >&5
+echo $ECHO_N "checking for ar flags... $ECHO_C" >&6
+if test -z "$ARFLAGS"; then
+  ARFLAGS="cru"
+fi
+
+echo "$as_me:$LINENO: result: $ARFLAGS" >&5
+echo "${ECHO_T}$ARFLAGS" >&6
+
+
+
+# sun cc -E leaves nasty # comment that chokes the fortran compiler, so we have to hope
+# that ye olde cpp is present.
+echo "$as_me:$LINENO: checking for /lib/cpp" >&5
+echo $ECHO_N "checking for /lib/cpp... $ECHO_C" >&6
+if test "${ac_cv_file__lib_cpp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/lib/cpp"; then
+  ac_cv_file__lib_cpp=yes
+else
+  ac_cv_file__lib_cpp=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file__lib_cpp" >&5
+echo "${ECHO_T}$ac_cv_file__lib_cpp" >&6
+if test $ac_cv_file__lib_cpp = yes; then
+  TRADITIONAL_CPP=yes
+else
+  TRADITIONAL_CPP=no
+fi
+
+
+if test "$TRADITIONAL_CPP" != "yes"; then
+   # Extract the first word of "cpp", so it can be a program name with args.
+set dummy cpp; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_BASIC_CPP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$BASIC_CPP"; then
+  ac_cv_prog_BASIC_CPP="$BASIC_CPP" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_BASIC_CPP="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_BASIC_CPP" && ac_cv_prog_BASIC_CPP="no"
+fi
+fi
+BASIC_CPP=$ac_cv_prog_BASIC_CPP
+if test -n "$BASIC_CPP"; then
+  echo "$as_me:$LINENO: result: $BASIC_CPP" >&5
+echo "${ECHO_T}$BASIC_CPP" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+   if test "$BASIC_CPP" = yes; then
+       CPP=cpp
+   else
+       { { echo "$as_me:$LINENO: error: Traditional cpp not found, just have to exit for for now." >&5
+echo "$as_me: error: Traditional cpp not found, just have to exit for for now." >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+else
+   CPP="/lib/cpp"
+fi
+
+case "$canonical_host_type" in
+  *-*-cygwin* | *-*-mingw*)
+	TRADITIONAL_CPP_FLAGS="-traditional-cpp"
+  ;;
+  *-*-linux* | *-*-gnu*)
+	TRADITIONAL_CPP_FLAGS="-traditional-cpp"
+  ;;
+  *)
+	TRADITIONAL_CPP_FLAGS=""
+  ;;
+esac
+
+
 
 
 
@@ -6627,7 +6630,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6630: \"$ac_link\") >&5
+(eval echo $as_me:6633: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6711,7 +6714,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6714: \"$ac_link\") >&5
+(eval echo $as_me:6717: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7458,7 +7461,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_verb"
-(eval echo $as_me:7461: \"$ac_link\") >&5
+(eval echo $as_me:7464: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -7542,7 +7545,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_cv_prog_fc_v"
-(eval echo $as_me:7545: \"$ac_link\") >&5
+(eval echo $as_me:7548: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -14380,11 +14383,6 @@ s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
 s,@MAINTAINER_MODE_FALSE@,$MAINTAINER_MODE_FALSE,;t t
 s,@MAINT@,$MAINT,;t t
 s,@canonical_host_type@,$canonical_host_type,;t t
-s,@BOURNE_SHELL@,$BOURNE_SHELL,;t t
-s,@RANLIB@,$RANLIB,;t t
-s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
-s,@AR@,$AR,;t t
-s,@ARFLAGS@,$ARFLAGS,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
@@ -14401,8 +14399,6 @@ s,@AMDEPBACKSLASH@,$AMDEPBACKSLASH,;t t
 s,@CCDEPMODE@,$CCDEPMODE,;t t
 s,@am__fastdepCC_TRUE@,$am__fastdepCC_TRUE,;t t
 s,@am__fastdepCC_FALSE@,$am__fastdepCC_FALSE,;t t
-s,@BASIC_CPP@,$BASIC_CPP,;t t
-s,@CPP@,$CPP,;t t
 s,@CXX@,$CXX,;t t
 s,@CXXFLAGS@,$CXXFLAGS,;t t
 s,@CCC@,$CCC,;t t
@@ -14416,6 +14412,13 @@ s,@ac_ct_FC@,$ac_ct_FC,;t t
 s,@F77@,$F77,;t t
 s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
+s,@BOURNE_SHELL@,$BOURNE_SHELL,;t t
+s,@RANLIB@,$RANLIB,;t t
+s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
+s,@AR@,$AR,;t t
+s,@ARFLAGS@,$ARFLAGS,;t t
+s,@BASIC_CPP@,$BASIC_CPP,;t t
+s,@CPP@,$CPP,;t t
 s,@GREP@,$GREP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@USE_64BIT_ARCH_TRUE@,$USE_64BIT_ARCH_TRUE,;t t
