*** empty log message ***
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@780 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/fem/configure b/fem/configure
--- a/fem/configure
+++ b/fem/configure
@@ -752,6 +752,7 @@ TEMPLATE_ARFLAGS
 library_path_var
 FCPPFLAGS
 LIBEXT
+UNIX_MATH_LIB
 LIBSOLVER_DEPS
 RM
 CP
@@ -1412,6 +1413,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-debug            Use debugging flags (environment variables override)
+  --with-stdcxxlib=<lib>  use std c++ library <lib>
   --with-64bits=yes(/no)  Try to compile using 64 bits (default)
   --with-mpi=yes  Use mpi (by default disabled)
   --with-mpi-dir=MPIDIR   give the path for MPI /usr/local/mpich
@@ -5060,6 +5062,233 @@ case "$canonical_host_type" in
 esac
 
 
+
+
+
+
+
+
+acx_check_stdcxxlib_save_LIBS=$LIBS
+acx_stdcxxlib_ok=no
+
+
+# Check whether --with-stdcxxlib or --without-stdcxxlib was given.
+if test "${with_stdcxxlib+set}" = set; then
+  withval="$with_stdcxxlib"
+
+fi;
+
+case $with_stdcxxlib in
+	yes | "") ;;
+	no) acx_stdcxxlib_ok=disable ;;
+	-* | */* | *.a | *.so | *.so.* | *.o) STDCXX_LIBS="$with_stdcxxlib" ;;
+	*) STDCXX_LIBS="-l$with_stdcxxlib" ;;
+esac
+
+if test x$STDCXX_LIBS != x; then
+	save_LIBS="$LIBS"; LIBS="$STDCXX_LIBS $LIBS"
+	{ echo "$as_me:$LINENO: checking for main in $STDCXX_LIBS" >&5
+echo $ECHO_N "checking for main in $STDCXX_LIBS... $ECHO_C" >&6; }
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  acx_stdcxx_lib_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+STDCXX_LIBS=""
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	{ echo "$as_me:$LINENO: result: $acx_stdcxx_lib_ok" >&5
+echo "${ECHO_T}$acx_stdcxx_lib_ok" >&6; }
+	LIBS="$save_LIBS"
+fi
+
+if test $acx_stdcxxlib_ok = no; then
+	{ echo "$as_me:$LINENO: checking for main in -lstdc++" >&5
+echo $ECHO_N "checking for main in -lstdc++... $ECHO_C" >&6; }
+if test "${ac_cv_lib_stdcpp_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lstdc++  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_stdcpp_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_stdcpp_main=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_stdcpp_main" >&5
+echo "${ECHO_T}$ac_cv_lib_stdcpp_main" >&6; }
+if test $ac_cv_lib_stdcpp_main = yes; then
+
+				   STDCXX_LIBS="-lstdc++"
+			           acx_stdcxxlib_ok=yes
+
+fi
+
+fi
+
+if test $acx_stdcxxlib_ok = no; then
+	{ echo "$as_me:$LINENO: checking for main in -lCstd" >&5
+echo $ECHO_N "checking for main in -lCstd... $ECHO_C" >&6; }
+if test "${ac_cv_lib_Cstd_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lCstd  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Cstd_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_Cstd_main=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_Cstd_main" >&5
+echo "${ECHO_T}$ac_cv_lib_Cstd_main" >&6; }
+if test $ac_cv_lib_Cstd_main = yes; then
+
+				   STDCXX_LIBS="-lCstd"
+			           acx_stdcxxlib_ok=yes
+
+fi
+
+fi
+
+
+if test $acx_stdcxxlib_ok = no; then
+	{ { echo "$as_me:$LINENO: error: Couldn't find std c++ library that is needed for linking." >&5
+echo "$as_me: error: Couldn't find std c++ library that is needed for linking." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+LIBS=$acx_check_stdcxxlib_save_LIBS
+
+if test "$acx_cv_compiler_ms" = "yes"; then
+	STDCXX_LIBS=""
+fi
 
 
 
@@ -13656,7 +13885,6 @@ echo "$as_me: error: libmatc $ELMER_LIBERRORMSG" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-
 { echo "$as_me:$LINENO: checking for main in -lm" >&5
 echo $ECHO_N "checking for main in -lm... $ECHO_C" >&6; }
 if test "${ac_cv_lib_m_main+set}" = set; then
@@ -13732,12 +13960,9 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_m_main" >&5
 echo "${ECHO_T}$ac_cv_lib_m_main" >&6; }
 if test $ac_cv_lib_m_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBM 1
-_ACEOF
-
-  LIBS="-lm $LIBS"
-
+  UNIX_MATH_LIB="-lm"
+else
+  UNIX_MATH_LIB=""
 fi
 
 
@@ -13858,7 +14083,7 @@ case "$canonical_host_type" in
 esac
 
 if test "$acx_cv_c_compiler_ms" = "yes"; then
-    EXTRA_LIBS="libelmersolver.lib -stack:500000000"
+    EXTRA_LIBS="-llibelmersolver -stack:500000000"
 fi
 
 TESTS_FCFLAGS="$TESTS_FCFLAGS $INCLUDE_MODULE_FLAG."
@@ -13918,6 +14143,7 @@ echo "${ECHO_T}defining library_path_var to be $library_path_var" >&6; }
 echo "${ECHO_T}defining FCPPFLAGS to be $FCPPFLAGS" >&6; }
 { echo "$as_me:$LINENO: result: defining LIBSOLVER_DEPS to be $LIBSOLVER_DEPS" >&5
 echo "${ECHO_T}defining LIBSOLVER_DEPS to be $LIBSOLVER_DEPS" >&6; }
+
 
 
 
@@ -14827,6 +15053,7 @@ s,@TEMPLATE_ARFLAGS@,$TEMPLATE_ARFLAGS,;t t
 s,@library_path_var@,$library_path_var,;t t
 s,@FCPPFLAGS@,$FCPPFLAGS,;t t
 s,@LIBEXT@,$LIBEXT,;t t
+s,@UNIX_MATH_LIB@,$UNIX_MATH_LIB,;t t
 s,@LIBSOLVER_DEPS@,$LIBSOLVER_DEPS,;t t
 s,@RM@,$RM,;t t
 s,@CP@,$CP,;t t
