Binary input/output for ModelDescription.src/SaveResult() and ModelDescription.src/LoadRestartFile().
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@1357 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/fem/configure b/fem/configure
--- a/fem/configure
+++ b/fem/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT canonical_host_type IBM_IS_PIECE_OF_SHIT_TRUE IBM_IS_PIECE_OF_SHIT_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE FC FCFLAGS ac_ct_FC F77 FFLAGS ac_ct_F77 BOURNE_SHELL RANLIB ac_ct_RANLIB AR ARFLAGS USE_WINDOWS_COMPILER_TRUE USE_WINDOWS_COMPILER_FALSE BASIC_CPP CPP EGREP USE_64BIT_ARCH_TRUE USE_64BIT_ARCH_FALSE B64FLAGS FLIBS FCLIBS LD_LIBRARY_PATH_VAR RPATH_FLAG SH_EXPALL_FLAG RPATH_ELMER mpi_dir mpi_lib_dir mpi_inc_dir lib_mpi MPI_LIBS MPI_INCLUDE_DIR MPI_F90 BLAS_LIBS LAPACK_LIBS HUTI_LIBS EIOF_LIBS ARPACK_LIBS PARPACK_LIBS UMFPACK_LIBS MATC_LIBS FORTRAN_CPP_FLAG USE_MPI_TRUE USE_MPI_FALSE USE_CPP_TRUE USE_CPP_FALSE USE_LOCAL_MPIF_H_TRUE USE_LOCAL_MPIF_H_FALSE SH_LDFLAGS SH_LD TESTS_FCFLAGS INCLUDE_MODULE_FLAG MESHGEN2D_LIBS FPICFLAG CPICFLAG CXXPICFLAG SHLEXT SHLLIB SHLBIN SHLEXT_VER SHLLIB_VER SHLBIN_VER SHLLINKEXT DLFCN_DIR SH_LD2 EXTRA_LIBS SH_LINKING_TO_FLAGS DL_LD DL_LDFLAGS MKOCTFILE_DL_LDFLAGS SONAME_FLAGS NO_OCT_FILE_STRIP RLD_FLAG TEMPLATE_AR TEMPLATE_ARFLAGS library_path_var FCPPFLAGS LIBEXT UNIX_MATH_LIB LIBSOLVER_DEPS RM CP MV MKDIR SOLVER_LIBS SOLVER_MPI_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT canonical_host_type IBM_IS_PIECE_OF_SHIT_TRUE IBM_IS_PIECE_OF_SHIT_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE FC FCFLAGS ac_ct_FC F77 FFLAGS ac_ct_F77 BOURNE_SHELL RANLIB ac_ct_RANLIB AR ARFLAGS USE_WINDOWS_COMPILER_TRUE USE_WINDOWS_COMPILER_FALSE BASIC_CPP CPP EGREP USE_64BIT_ARCH_TRUE USE_64BIT_ARCH_FALSE B64FLAGS FLIBS FCLIBS LD_LIBRARY_PATH_VAR RPATH_FLAG SH_EXPALL_FLAG RPATH_ELMER mpi_dir mpi_lib_dir mpi_inc_dir lib_mpi MPI_LIBS MPI_INCLUDE_DIR MPI_F90 BLAS_LIBS LAPACK_LIBS HUTI_LIBS EIOF_LIBS ARPACK_LIBS PARPACK_LIBS UMFPACK_LIBS MATC_LIBS FORTRAN_CPP_FLAG USE_MPI_TRUE USE_MPI_FALSE USE_CPP_TRUE USE_CPP_FALSE USE_LOCAL_MPIF_H_TRUE USE_LOCAL_MPIF_H_FALSE SH_LDFLAGS SH_LD UPPERCASEMODS_TRUE UPPERCASEMODS_FALSE modput_opt TESTS_FCFLAGS INCLUDE_MODULE_FLAG MESHGEN2D_LIBS FPICFLAG CPICFLAG CXXPICFLAG SHLEXT SHLLIB SHLBIN SHLEXT_VER SHLLIB_VER SHLBIN_VER SHLLINKEXT DLFCN_DIR SH_LD2 EXTRA_LIBS SH_LINKING_TO_FLAGS DL_LD DL_LDFLAGS MKOCTFILE_DL_LDFLAGS SONAME_FLAGS NO_OCT_FILE_STRIP RLD_FLAG TEMPLATE_AR TEMPLATE_ARFLAGS library_path_var FCPPFLAGS LIBEXT UNIX_MATH_LIB LIBSOLVER_DEPS RM CP MV MKDIR SOLVER_LIBS SOLVER_MPI_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1895,6 +1895,11 @@ else
 fi
 
   MAINT=$MAINTAINER_MODE_TRUE
+
+
+
+
+
 
 
 
@@ -3612,7 +3617,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3615:" \
+echo "$as_me:3620:" \
      "checking for Fortran compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -3847,7 +3852,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3850:" \
+echo "$as_me:3855:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5711,7 +5716,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5714: \"$ac_link\") >&5
+(eval echo $as_me:5719: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5789,7 +5794,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5792: \"$ac_link\") >&5
+(eval echo $as_me:5797: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6527,7 +6532,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_verb"
-(eval echo $as_me:6530: \"$ac_link\") >&5
+(eval echo $as_me:6535: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -6605,7 +6610,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_cv_prog_fc_v"
-(eval echo $as_me:6608: \"$ac_link\") >&5
+(eval echo $as_me:6613: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -7331,14 +7336,14 @@ case "$ac_cv_fc_mangling" in
   "upper case, no underscore, no extra underscore" | "upper case, no underscores")
 
 cat >>confdefs.h <<\_ACEOF
-#define ELMER_LINKTYP 2
+#define ELMER_LINKTYP 1
 _ACEOF
 
   ;;
   "lower case, no underscore, no extra underscore" | "lower case, no underscores" )
 
 cat >>confdefs.h <<\_ACEOF
-#define ELMER_LINKTYP 3
+#define ELMER_LINKTYP 1
 _ACEOF
 
   ;;
@@ -7352,7 +7357,7 @@ _ACEOF
   "lower case, underscore, extra underscore" | "lower case, double underscores")
 
 cat >>confdefs.h <<\_ACEOF
-#define ELMER_LINKTYP 4
+#define ELMER_LINKTYP 1
 _ACEOF
 
   ;;
@@ -7362,6 +7367,9 @@ echo "$as_me: error: Unknown sort of Fortran name mangling" >&2;}
    { (exit 1); exit 1; }; }
   ;;
 esac
+
+
+
 
 
 
@@ -12997,6 +13005,84 @@ esac
 
 
 
+echo "$as_me:$LINENO: checking for *.mod-file naming convention" >&5
+echo $ECHO_N "checking for *.mod-file naming convention... $ECHO_C" >&6
+if test "${modfilename+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+mkdir conftestdir
+cd conftestdir
+cat > foo.f90 << STOP
+module modulename
+    integer :: bar
+end module modulename
+STOP
+${FC-fc} -c foo.f90
+modfilename=""
+for m in modulename.mod MODULENAME.mod; do
+    if test -r $m ; then
+        modfilename=$m
+        break;
+    fi
+done
+cd ..
+rm -rf conftestdir
+if test ""$modfilename = "" ; then
+    { echo "$as_me:$LINENO: WARNING: Can't find *.mod-file naming conventions for ${FC-fc}" >&5
+echo "$as_me: WARNING: Can't find *.mod-file naming conventions for ${FC-fc}" >&2;}
+fi
+
+fi
+echo "$as_me:$LINENO: result: $modfilename" >&5
+echo "${ECHO_T}$modfilename" >&6
+
+
+
+if test $modfilename = "MODULENAME.mod"; then
+  UPPERCASEMODS_TRUE=
+  UPPERCASEMODS_FALSE='#'
+else
+  UPPERCASEMODS_TRUE='#'
+  UPPERCASEMODS_FALSE=
+fi
+
+echo "$as_me:$LINENO: checking for option to tell ${FC-fc} where to put *.mod-files" >&5
+echo $ECHO_N "checking for option to tell ${FC-fc} where to put *.mod-files... $ECHO_C" >&6
+if test "${modput_opt+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+mkdir conftestdir
+cd conftestdir
+mkdir src
+cd src
+cat > foo.f90 << STOP
+module foo
+    integer :: bar
+end module foo
+STOP
+modput_opt=""
+for opt in -M -J -moddir= '-module '; do
+    ${FC-fc} -c foo.f90 ${opt}.. > /dev/null 2>&1
+    if test -r ../foo.mod || test -r ../FOO.mod; then
+        modput_opt=$opt
+        break
+    fi
+done
+cd ../..
+rm -rf conftestdir
+if test ""$modput_opt = "" ; then
+    { echo "$as_me:$LINENO: WARNING: Can't find *.mod-file put option for ${FC-fc}" >&5
+echo "$as_me: WARNING: Can't find *.mod-file put option for ${FC-fc}" >&2;}
+fi
+
+fi
+echo "$as_me:$LINENO: result: $modput_opt" >&5
+echo "${ECHO_T}$modput_opt" >&6
+
+
+
 SOLVER_LIBS="$LIBS $ARPACK_LIBS $PARPACK_LIBS $UMFPACK_LIBS $HUTI_LIBS $MATC_LIBS $EIOF_LIBS $LIBS $LAPACK_LIBS $BLAS_LIBS $FCLIBS $FLIBS $STDCXX_LIBS"
 
 case "$canonical_host_type" in
@@ -13130,7 +13216,7 @@ _ACEOF
           ac_config_files="$ac_config_files src/elmerf90"
 
 
-                                                            ac_config_files="$ac_config_files Makefile Makeconf src/Makefile src/view3d/Makefile src/viewaxis/Makefile tests/Makefile"
+                                                                                ac_config_files="$ac_config_files Makefile Makeconf src/Makefile src/view3d/Makefile src/viewaxis/Makefile src/binio/Makefile src/binio/test/Makefile tests/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -13289,6 +13375,13 @@ if test -z "${USE_LOCAL_MPIF_H_TRUE}" && test -z "${USE_LOCAL_MPIF_H_FALSE}"; th
   { { echo "$as_me:$LINENO: error: conditional \"USE_LOCAL_MPIF_H\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"USE_LOCAL_MPIF_H\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${UPPERCASEMODS_TRUE}" && test -z "${UPPERCASEMODS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"UPPERCASEMODS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"UPPERCASEMODS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -13743,6 +13836,8 @@ do
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "src/view3d/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/view3d/Makefile" ;;
   "src/viewaxis/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/viewaxis/Makefile" ;;
+  "src/binio/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/binio/Makefile" ;;
+  "src/binio/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/binio/test/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
@@ -13942,6 +14037,9 @@ s,@USE_LOCAL_MPIF_H_TRUE@,$USE_LOCAL_MPIF_H_TRUE,;t t
 s,@USE_LOCAL_MPIF_H_FALSE@,$USE_LOCAL_MPIF_H_FALSE,;t t
 s,@SH_LDFLAGS@,$SH_LDFLAGS,;t t
 s,@SH_LD@,$SH_LD,;t t
+s,@UPPERCASEMODS_TRUE@,$UPPERCASEMODS_TRUE,;t t
+s,@UPPERCASEMODS_FALSE@,$UPPERCASEMODS_FALSE,;t t
+s,@modput_opt@,$modput_opt,;t t
 s,@TESTS_FCFLAGS@,$TESTS_FCFLAGS,;t t
 s,@INCLUDE_MODULE_FLAG@,$INCLUDE_MODULE_FLAG,;t t
 s,@MESHGEN2D_LIBS@,$MESHGEN2D_LIBS,;t t
