make dist fixes
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@486 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/fem/configure b/fem/configure
--- a/fem/configure
+++ b/fem/configure
@@ -693,7 +693,6 @@ B64FLAGS
 FLIBS
 FCLIBS
 LD_LIBRARY_PATH_VAR
-SH_EXPALL_FLAG
 mpi_dir
 mpi_lib_dir
 mpi_inc_dir
@@ -8750,7 +8749,6 @@ case "$canonical_host_type" in
   ;;
   *-*-darwin*)
     SH_LDFLAGS='-dynamiclib -undefined dynamic_lookup -single_module $(LDFLAGS)'
-    SHLEXT="dylib"
     LD_LIBRARY_PATH_VAR=DYLD_LIBRARY_PATH
   ;;
   *-*-cygwin* | *-*-mingw*)
@@ -8759,8 +8757,6 @@ case "$canonical_host_type" in
        SH_LD=$CC
   ;;
   *-*-linux* | *-*-gnu*)
-	SH_LDFLAGS="-shared"
-	SH_EXPALL_FLAG="-Wl,-export-dynamic"
   ;;
   i[3456]86-*-sco3.2v5*)
     SH_LDFLAGS="-G"
@@ -8771,7 +8767,6 @@ case "$canonical_host_type" in
     LD_LIBRARY_PATH_VAR=LIBPATH
   ;;
   hppa*-hp-hpux*)
-    SHLEXT=sl
     SH_LDFLAGS="-shared -fPIC"
   ;;
   *-sgi-*)
@@ -8787,7 +8782,6 @@ case "$canonical_host_type" in
     fi
   ;;
 esac
-
 
 
 
@@ -8810,6 +8804,148 @@ if $SHARED_LIBS || $ENABLE_DYNAMIC_LINKING; then
 
   ### Check for dyld first since OS X can have a non-standard libdl
 
+  if test "${ac_cv_header_Mach_O_dyld_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for Mach-O/dyld.h" >&5
+echo $ECHO_N "checking for Mach-O/dyld.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_Mach_O_dyld_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_Mach_O_dyld_h" >&5
+echo "${ECHO_T}$ac_cv_header_Mach_O_dyld_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking Mach-O/dyld.h usability" >&5
+echo $ECHO_N "checking Mach-O/dyld.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <Mach-O/dyld.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking Mach-O/dyld.h presence" >&5
+echo $ECHO_N "checking Mach-O/dyld.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Mach-O/dyld.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: Mach-O/dyld.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: Mach-O/dyld.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Mach-O/dyld.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: Mach-O/dyld.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: Mach-O/dyld.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: Mach-O/dyld.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Mach-O/dyld.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: Mach-O/dyld.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Mach-O/dyld.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: Mach-O/dyld.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Mach-O/dyld.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: Mach-O/dyld.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Mach-O/dyld.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: Mach-O/dyld.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Mach-O/dyld.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: Mach-O/dyld.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for Mach-O/dyld.h" >&5
+echo $ECHO_N "checking for Mach-O/dyld.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_Mach_O_dyld_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_Mach_O_dyld_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_Mach_O_dyld_h" >&5
+echo "${ECHO_T}$ac_cv_header_Mach_O_dyld_h" >&6; }
+
+fi
+
+
+  if test "$ac_cv_header_Mach_O_dyld_h" = yes; then
+    dyld_api=true
+  else
 
 { echo "$as_me:$LINENO: checking for shl_load in -ldld" >&5
 echo $ECHO_N "checking for shl_load in -ldld... $ECHO_C" >&6; }
@@ -9468,6 +9604,7 @@ done
 	fi
       fi
     fi
+  fi
 
   if $dlopen_api; then
     DL_API_MSG="(dlopen)"
@@ -13537,7 +13674,7 @@ _ACEOF
           ac_config_files="$ac_config_files tests/runtests"
 
 
-                                                                                                              ac_config_files="$ac_config_files Makefile Makeconf src/Makefile src/arpack/Makefile src/parpack/Makefile src/view3d/Makefile src/viewaxis/Makefile tests/Makefile src/elmergrid/Makefile src/elmergrid/metis/Makefile src/meshgen2d/Makefile"
+                                                                                                                        ac_config_files="$ac_config_files Makefile Makeconf src/Makefile src/arpack/Makefile src/parpack/Makefile src/view3d/Makefile src/viewaxis/Makefile tests/Makefile src/elmergrid/Makefile src/elmergrid/metis/Makefile src/meshgen2d/Makefile src/meshgen2d/include/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -14145,6 +14282,7 @@ do
   "src/elmergrid/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/elmergrid/Makefile" ;;
   "src/elmergrid/metis/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/elmergrid/metis/Makefile" ;;
   "src/meshgen2d/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/meshgen2d/Makefile" ;;
+  "src/meshgen2d/include/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/meshgen2d/include/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -14320,7 +14458,6 @@ s,@B64FLAGS@,$B64FLAGS,;t t
 s,@FLIBS@,$FLIBS,;t t
 s,@FCLIBS@,$FCLIBS,;t t
 s,@LD_LIBRARY_PATH_VAR@,$LD_LIBRARY_PATH_VAR,;t t
-s,@SH_EXPALL_FLAG@,$SH_EXPALL_FLAG,;t t
 s,@mpi_dir@,$mpi_dir,;t t
 s,@mpi_lib_dir@,$mpi_lib_dir,;t t
 s,@mpi_inc_dir@,$mpi_inc_dir,;t t
