SADd
git-svn-id: svn://svn.code.sf.net/p/elmerfem/code/trunk@238 04224531-1f84-46d8-96ce-875b9e37dce3

diff --git a/fem/configure b/fem/configure
--- a/fem/configure
+++ b/fem/configure
@@ -669,7 +669,6 @@ RANLIB
 ac_ct_RANLIB
 AR
 ARFLAGS
-TRADITIONAL_CPP
 BASIC_CPP
 CPP
 CXX
@@ -4760,40 +4759,27 @@ fi
 
 # sun cc -E leaves nasty # comment that chokes the fortran compiler, so we have to hope
 # that ye olde cpp is present.
-# Extract the first word of "/lib/cpp", so it can be a program name with args.
-set dummy /lib/cpp; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_TRADITIONAL_CPP+set}" = set; then
+echo "$as_me:$LINENO: checking for /lib/cpp" >&5
+echo $ECHO_N "checking for /lib/cpp... $ECHO_C" >&6
+if test "${ac_cv_file__lib_cpp+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  if test -n "$TRADITIONAL_CPP"; then
-  ac_cv_prog_TRADITIONAL_CPP="$TRADITIONAL_CPP" # Let the user override the test.
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/lib/cpp"; then
+  ac_cv_file__lib_cpp=yes
 else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_TRADITIONAL_CPP="yes"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  test -z "$ac_cv_prog_TRADITIONAL_CPP" && ac_cv_prog_TRADITIONAL_CPP="no"
+  ac_cv_file__lib_cpp=no
 fi
 fi
-TRADITIONAL_CPP=$ac_cv_prog_TRADITIONAL_CPP
-if test -n "$TRADITIONAL_CPP"; then
-  echo "$as_me:$LINENO: result: $TRADITIONAL_CPP" >&5
-echo "${ECHO_T}$TRADITIONAL_CPP" >&6
+echo "$as_me:$LINENO: result: $ac_cv_file__lib_cpp" >&5
+echo "${ECHO_T}$ac_cv_file__lib_cpp" >&6
+if test $ac_cv_file__lib_cpp = yes; then
+  TRADITIONAL_CPP=yes
 else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
+  TRADITIONAL_CPP=no
 fi
 
 
@@ -5525,7 +5511,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5528:" \
+echo "$as_me:5514:" \
      "checking for Fortran compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version >&5\"") >&5
@@ -5772,7 +5758,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5775:" \
+echo "$as_me:5761:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version >&5\"") >&5
@@ -7490,7 +7476,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7493: \"$ac_link\") >&5
+(eval echo $as_me:7479: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7574,7 +7560,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7577: \"$ac_link\") >&5
+(eval echo $as_me:7563: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8321,7 +8307,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_verb"
-(eval echo $as_me:8324: \"$ac_link\") >&5
+(eval echo $as_me:8310: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -8405,7 +8391,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_cv_prog_fc_v"
-(eval echo $as_me:8408: \"$ac_link\") >&5
+(eval echo $as_me:8394: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -15069,7 +15055,6 @@ s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@AR@,$AR,;t t
 s,@ARFLAGS@,$ARFLAGS,;t t
-s,@TRADITIONAL_CPP@,$TRADITIONAL_CPP,;t t
 s,@BASIC_CPP@,$BASIC_CPP,;t t
 s,@CPP@,$CPP,;t t
 s,@CXX@,$CXX,;t t
